### PR TITLE
Fix signature validation

### PR DESCRIPTION
**Pull request by stayallive**
I noticed that running this request to the websocket server yields an invalid signature error.

```php
$pusher->get_channels(['filter_by_prefix' => 'presence-global']);
```

I noticed that the signatures are not generated as the Pusher lib and server expects/validates them.

So I fixed that and modified all tests to use the correct way (according to the `Pusher` library).

----

Edit: After more testing this is broken since the route parameters are added as query params causing it to mess up the signature creation...

----

Edit edit: This now works like it should and ready for review

### CODE REVIEW

**Comment by stayallive** [comment]
@mpociot @freekmurze I would like to have your opinion.

To correctly validate the signature we cannot have `appId`, `appKey` & `channelName` in the query params, but I'm not seeing any way to have them being recognized as actual route params because Ratchet is not very flexible on how the route is matched and what happens after.

So to fix any extra parameter added to the request being ignored en thus rendering the signature invalid too I added those to a blacklist to be able to reconstruct the signature how it should be with params that are not route params.

However this feels a bit dirty... we could also special case `filter_by_prefix` since it's the only actual query param that is being used in the entire (tiny) REST api. However would be cool if we can build upon the Pusher compat with some extra endpoints possibly that will make it more flexible doing it the way it's now...

Let me know what you think on what route (heh, no pun intended) to take with this.

**Comment by stayallive** [comment]
Rebased with master to fix conflicts.

**Comment by mpociot** [comment]
@stayallive You mention "After more testing this is broken since the route parameters are added as query params causing it to mess up the signature creation..."
So..is this broken?

**Comment by stayallive** [comment]
Please read my update: https://github.com/beyondcode/laravel-websockets/pull/38#issuecomment-445341343

It now works great, but not sure if there is a better way I'm missing.

This still feels a bit wrong to me to whitelist/blacklist the query parameter names but I can see no way to (without rewriting the router and possibly things in Ratchet) to know which query params are coming from the route parameters and which come from the user.

https://github.com/beyondcode/laravel-websockets/blob/8f4247936ac0b9d602ea053164153b3c2d807c61/src/HttpApi/Controllers/Controller.php#L88-L93

**Comment by stayallive** [comment]
@mpociot can you let me know what you plan is with this? 😄 

Want to know if I need to merge 1.0.3 in my fork or if I can fix something to get this moving forward.

**Comment by stayallive** [comment]
@mpociot can you let me know what you plan is with this? 😄

**Pull request merged**
