### PR TITLE
Fix Symfony deprecation error in TriggerEventController

### LINKED ISSUE #1146: Exception `InvalidArgumentException`
In some instances the following error is thrown:

Exception `InvalidArgumentException` thrown: `Expected a scalar value as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::get()", "array" given.

I believe this is due to Symfony no longer accepting scalar default values in inputBag which is used in TriggerEventController.php on line 19.

### PR DESCRIPTION
**Pull request by pajkho**
Should fix #1146 that is caused by Symfony deprecating non-scalar values in InputBag.php.

### CODE REVIEW

**Comment by aalyusuf** [comment]
``optional(..)`` should be removed as it will not work with foreach, so the fix should be:

``$channels = $payload->all()['channels'] ?? [];``

**Comment by ManuelLeiner** [comment]
> `optional(..)` should be removed as it will not work with foreach, so the fix should be:
> 
> `$channels = $payload->all()['channels'] ?? [];`

Works for me. 

After upgrading laravel/dusk from 7.9.1 to 7.9.2 via dependabot last week the websockets stopped working. I could verify with `git bisect` that this is the bad commit. Quickly changing that one line in the vendor files makes it work again.

Here is the list of updates that came in by merging the dependabot PR for laravel/dusk 7.9.2 and as we can see there are some symfony patches.

```
Package operations: 1 install, 18 updates, 0 removals
  - Upgrading symfony/finder (v6.3.0 => v6.3.3): Extracting archive
  - Upgrading symfony/var-dumper (v6.3.1 => v6.3.3): Extracting archive
  - Upgrading symfony/css-selector (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/routing (v6.3.1 => v6.3.3): Extracting archive
  - Upgrading symfony/process (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/mime (v6.3.0 => v6.3.3): Extracting archive
  - Upgrading symfony/event-dispatcher (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/http-foundation (v6.3.1 => v6.3.2): Extracting archive
  - Upgrading symfony/error-handler (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/http-kernel (v6.3.1 => v6.3.3): Extracting archive
  - Upgrading symfony/string (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/console (v6.3.0 => v6.3.2): Extracting archive
  - Upgrading symfony/translation (v6.3.0 => v6.3.3): Extracting archive
  - Upgrading league/mime-type-detection (1.11.0 => 1.12.0): Extracting archive
  - Upgrading nette/utils (v4.0.0 => v4.0.1): Extracting archive
  - Upgrading laravel/framework (v10.16.1 => v10.17.1): Extracting archive
  - Installing laravel/prompts (v0.1.3): Extracting archive
  - Upgrading phpunit/phpunit (10.2.6 => 10.2.7): Extracting archive
  - Upgrading laravel/dusk (v7.9.1 => v7.9.2): Extracting archive
```

**Comment by aalyusuf** [comment]
> > `optional(..)` should be removed as it will not work with foreach, so the fix should be:
> > `$channels = $payload->all()['channels'] ?? [];`
> 
> Works for me.
> 
> After upgrading laravel/dusk from 7.9.1 to 7.9.2 via dependabot last week the websockets stopped working. I could verify with `git bisect` that this is the bad commit. Quickly changing that one line in the vendor files makes it work again.
> 
> Here is the list of updates that came in by merging the dependabot PR for laravel/dusk 7.9.2 and as we can see there are some symfony patches.
> 
> ```
> Package operations: 1 install, 18 updates, 0 removals
>   - Upgrading symfony/finder (v6.3.0 => v6.3.3): Extracting archive
>   - Upgrading symfony/var-dumper (v6.3.1 => v6.3.3): Extracting archive
>   - Upgrading symfony/css-selector (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/routing (v6.3.1 => v6.3.3): Extracting archive
>   - Upgrading symfony/process (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/mime (v6.3.0 => v6.3.3): Extracting archive
>   - Upgrading symfony/event-dispatcher (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/http-foundation (v6.3.1 => v6.3.2): Extracting archive
>   - Upgrading symfony/error-handler (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/http-kernel (v6.3.1 => v6.3.3): Extracting archive
>   - Upgrading symfony/string (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/console (v6.3.0 => v6.3.2): Extracting archive
>   - Upgrading symfony/translation (v6.3.0 => v6.3.3): Extracting archive
>   - Upgrading league/mime-type-detection (1.11.0 => 1.12.0): Extracting archive
>   - Upgrading nette/utils (v4.0.0 => v4.0.1): Extracting archive
>   - Upgrading laravel/framework (v10.16.1 => v10.17.1): Extracting archive
>   - Installing laravel/prompts (v0.1.3): Extracting archive
>   - Upgrading phpunit/phpunit (10.2.6 => 10.2.7): Extracting archive
>   - Upgrading laravel/dusk (v7.9.1 => v7.9.2): Extracting archive
> ```

optional(..) returns an object of type `Illuminate/Support/Optional` and is not iterable, so foreach will not work, you can test using :
```
        $arr = optional([1, 2]);
        var_dump(is_iterable($arr));
```
and optional() is never null so using it with null coalesce isn't correct either and an empty array will never be returned.

The error may be gone but the channels shouldn't receive anything.

**Comment by ManuelLeiner** [comment]
Sorry for the confusion. The line of code you suggested works. 👍 

```
$channels = $payload->all()['channels'] ?? [];
```

I didn't try the optional.

Everything looks good now and happily updates via websockets in the frontend.

**Comment by ManuelLeiner** [comment]
It starts breaking with [laravel/framework v10.17.0](https://github.com/laravel/framework/releases/tag/v10.17.0)
 
https://github.com/laravel/framework/pull/47914

**Comment by hamdallahjodah** [comment]
@ManuelLeiner Please any update on this?

**Comment by pajkho** [comment]
Sorry for the late reply. I have updated the code now as suggested.

**Comment by ManuelLeiner** [comment]
> @ManuelLeiner Please any update on this?

I am not really involved in this project.

@mpociot Moin Marcel, what do you think? Is it something that needs to be fixed here?

**Comment by ManuelLeiner** [comment]
A workaround for Laravel 10 is to downgrade the framework to v10.16.1.

```bash
composer require laravel/framework:10.16.1
```

You might have to downgrade some other dependencies, e.g. Jetstream, as well.

**Comment by ManuelLeiner** [comment]
@sschlein @mechelon, apologies for tagging you both. Is there any chance of resolving this problem?

**Comment by parallels999** [comment]
No changes since [Oct 2022](https://github.com/beyondcode/laravel-websockets/commits/master)

**Comment by dbohn** [comment]
For anyone, who is still looking into how to fix this in their own application without waiting for a new release, the following approach could be used:

In your Laravel app, create a copy of the `TriggerEventController.php` class, in my case, I stored it in the `App\Websockets\Server\Controllers` namespace:

```php
<?php

namespace App\Websockets\Server\Controllers;

use BeyondCode\LaravelWebSockets\Dashboard\DashboardLogger;
use BeyondCode\LaravelWebSockets\Facades\StatisticsLogger;
use BeyondCode\LaravelWebSockets\HttpApi\Controllers\Controller;
use Illuminate\Http\Request;

class TriggerEventController extends Controller
{
    public function __invoke(Request $request)
    {
        $this->ensureValidSignature($request);
        $payload = $request->json();

        if ($payload->has('channel')) {
            $channels = [$payload->get('channel')];
        } else {
            $channels = $payload->all()['channels'] ?? [];

            if (is_string($channels)) {
                $channels = [$channels];
            }
        }

        foreach ($channels as $channelName) {
            $channel = $this->channelManager->find($request->appId, $channelName);

            optional($channel)->broadcastToEveryoneExcept([
                'channel' => $channelName,
                'event' => $request->json()->get('name'),
                'data' => $request->json()->get('data'),
            ], $request->json()->get('socket_id'));

            DashboardLogger::apiMessage(
                $request->appId,
                $channelName,
                $request->json()->get('name'),
                $request->json()->get('data')
            );

            StatisticsLogger::apiMessage($request->appId);
        }

        return (object) [];
    }
}
```

Then we create a new `Router class`, that extends `\BeyondCode\LaravelWebSockets\Server\Router` and override the `echo` method, that registers the route for this endpoint. In the override, make sure to reference your own fixed version of the `TriggerEventController` class:

```php
<?php

namespace App\Websockets\Server;

use App\Websockets\Server\Controllers\TriggerEventController;
use BeyondCode\LaravelWebSockets\HttpApi\Controllers\FetchChannelController;
use BeyondCode\LaravelWebSockets\HttpApi\Controllers\FetchChannelsController;
use BeyondCode\LaravelWebSockets\HttpApi\Controllers\FetchUsersController;
use BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler;

class Router extends \BeyondCode\LaravelWebSockets\Server\Router
{
    public function echo()
    {
        $this->get('/app/{appKey}', WebSocketHandler::class);

        $this->post('/apps/{appId}/events', TriggerEventController::class);
        $this->get('/apps/{appId}/channels', FetchChannelsController::class);
        $this->get('/apps/{appId}/channels/{channelName}', FetchChannelController::class);
        $this->get('/apps/{appId}/channels/{channelName}/users', FetchUsersController::class);
    }
}
```

Finally, in your `AppServiceProvider`'s `register` method (or any other provider, that you find fitting), update the `websockets.router` binding to point to your own router implementation:

```php
$this->app->singleton('websockets.router', function () {
    return new \App\Websockets\Server\Router();
});
```

Restart your websocket:serve command and you should be able to send broadcasts again!

**Comment by mpociot** [comment]
Thank you for the PR and sorry for the delay in merging this 🙈

**Pull request merged**
