### PR TITLE
[2.x] Async Redis queue driver

### LINKED ISSUE #190: Bi-directional broadcasting with Laravel echo
I have a server configured for multi tenancy, I can broadcast events with private channels from my applications to front end clients using the Laravel echo client to listen for events but I actually wish to emit events from the front end too, to trigger events on back end. 

 Is this possible with this package or is this strictly server to client broadcasting only?

### PR DESCRIPTION
**Pull request by rennokki**
Closes #190 

## Description

This PR adds a new `async-redis` connection that should be used in case you use Redis Queue features within the WebSockets server. It can also be set to default, because when no PHPReact Redis instance is available, it uses the default Redis connection.

## Tests
Tests were taken from the following files, to ensure compatibility with the default Laravel's Redis queue/jobs tests:

- https://github.com/laravel/framework/blob/8.x/tests/Queue/QueueRedisQueueTest.php
- https://github.com/laravel/framework/blob/8.x/tests/Queue/QueueRedisJobTest.php

### Async Redis Queue

The default Redis connection also interacts with the queues. Since you might want to dispatch jobs on Redis from the server, you can encounter an anti-pattern of using a blocking I/O connection (like PhpRedis or PRedis) within the WebSockets server.

To solve this issue, you can configure the built-in queue driver that uses the Async Redis connection when it's possible, like within the WebSockets server. It's highly recommended to switch your queue to it if you are going to use the queues within the server controllers, for example.

Add the `async-redis` queue driver to your list of connections. The configuration parameters are compatible with the default `redis` driver:

```php
'connections' => [
    'async-redis' => [
        'driver' => 'async-redis',
        'connection' => env('WEBSOCKETS_REDIS_REPLICATION_CONNECTION', 'default'),
        'queue' => env('REDIS_QUEUE', 'default'),
        'retry_after' => 90,
        'block_for' => null,
    ],
]
```

Also, make sure that the default queue driver is set to `async-redis`:

```
QUEUE_CONNECTION=async-redis
```

### CODE REVIEW

**Comment by francislavoie** [comment]
Seems alright to me.

I think changes were made to the RedisQueue implementation since I last looked at it (Laravel 5.6 ish) such that it now just fires off the redis command and doesn't care about the result. I thought more work would need to be done to handle promises and such.

Seems alright though, as long as basically just `push` and `later` are used to publish jobs.

**Comment by rennokki** [comment]
Yes, I have checked the inherited queue class and it seems like all it does is to push it to the queue, without caring too much about the result. So as long as the tests check if the `zadd` is called with the proper job details. Either way, when the channel manager is bind to the container it would use the client (like in the Server command loop), but otherwise, it can be used in reverse-compatibility with the default `redis` driver without any problem.

**Comment by deantheiceman** [comment]
@rennokki Could you clarify in the docs is it everything which should use `async-redis` ?

If so, laravel horizon is no longer compatitable:

```
local.ERROR: Call to undefined method BeyondCode\LaravelWebSockets\Queue\AsyncRedisQueue::readyNow() {"exception":"[object] (Error(code: 0): Call to undefined method BeyondCode\\LaravelWebSockets\\Queue\\AsyncRedisQueue::readyNow() at /var/www/html/vendor/laravel/horizon/src/AutoScaler.php:80
```

**Comment by Fenslau** [comment]
@rennokki
InvalidArgumentException

  No connector for [async-redis].
But I configured all as it was in Doc....

**Pull request merged**
