### PR TITLE
Add the ability to configure middleware.

### LINKED ISSUE #22: Dashboard in Production?
I'm trying to run the dashboard in production and limit its access to specific users but it looks like the `$user` var in Gate's definition is always `null` for some reason.

How can I run it with limited access to specific users?

P.S. I used the same code as in the docs. It appears there is no auth info in the request payload when the dashboard is running.

### PR DESCRIPTION
**Pull request by irazasyed**
Fixes #22

### CODE REVIEW

**Comment by irazasyed** [comment]
@mpociot @freekmurze Can we have some attention on this issue? It's working fine and I've been testing it for the last few days without any issues. Would be great if it's merged.

**Comment by acacha** [comment]
We also need this! Very useful @irazasyed

**Comment by vesper8** [comment]
will this allow to access the dashboard without a user at all? I mean, can I disable the authorize completely? This is what I do for Horizon/Telescope

I comment out the Authorize middleware completely and replace it by 'under-construction'

from https://github.com/larsjanssen6/underconstruction

This way I can protect my admin routes with a 4 digit pin and don't need to have a user system available at all on some of my apps

**Comment by irazasyed** [comment]
@vesper8 Yes, You can do that.

**Comment by mpociot** [comment]
Thank you for the PR. This was now part of another PR that just got merged.

**Pull request closed without merging**
