### PR TITLE
Make TriggerEventController accept both 'channel' and 'channels'.

### LINKED ISSUE #1041: Websockets not working with pusher-php-server 7.2
Hello, after pusher-php-server has been updated to version 7.2 websockets stopped working. I'm using Laravel Echo and the initial connection to private channel is successful, but then I'm not getting any events broadcasted on that channel. With pusher-php-server 7.0.2 everything works fine. Is the new version incompatible with Laravel Websockets and should I wait for an update?

### PR DESCRIPTION
**Pull request by madpilot78**
This is just a backport of a small part of commit fb958fb851

It should fix #1041.

The same issue is also reported in pusher/pusher-http-php#351.

### CODE REVIEW

**Comment by Wernke96** [comment]
@mpociot can you look at this?

**Review by adriangornypl — APPROVED** [review]
LGTM :)

**Comment by adriangornypl** [comment]
Definitely a good idea :) Waiting with fingers crossed ^^

**Review by Wernke96 — APPROVED** [review]

**Comment by tomvo** [comment]
🙇

**Comment by tomvo** [comment]
can this merge be tagged with a new version?

**Comment by blackjak231** [comment]
@mpociot Can we expect a new release of 1.x with this fix soon ?

**Pull request merged**
