### PR TITLE
Fix compatibility with laravel/passport

### PR DESCRIPTION
**Pull request by ricardo-lobo**
Addresses #331

### CODE REVIEW

**Comment by irazasyed** [comment]
Can we have this merged please? Unable to update this package in L7.

**Comment by pawel-marciniak** [comment]
I'm waiting for it too.

**Comment by irazasyed** [comment]
@freekmurze @mpociot Please merge this?

**Comment by dsampaolo** [comment]
Same here. Thank you !

**Comment by countnoobula** [comment]
Same here please ❤️

**Comment by navaer** [comment]
Need help with this too, there is also error on Laravel 6.18.1 and "laravel/passport": "^8.4".

**Comment by backstageel** [comment]
waiting for this to be merged

**Comment by kryp7ik** [comment]
I just upgraded to Laravel 7 and was having the same issue however I updated this package to be ^1.4 and also installed nyholm/psr7.  After installing nyholm/psr7, Passport is now working without having to upgrade the symfony/psr-http-message-bridge package.  Granted I only use Passport in a very limited scope so this may not help for all use cases of Passport.  It would be nice for this issue to be resolved so the Symfony package can be updated but just wanted to share my experience in case it helps anyone else.

**Comment by timhaak** [comment]
Any progress on this pull request?

Just wondering if there is a problem that is preventing a merge.

More asking so that we can possibly help.

**Comment by gdebrauwer** [comment]
@freekmurze @mpociot could you have a look at this PR? it's preventing a lot of us from upgrading to Laravel 7

**Comment by backstageel** [comment]
For anyone who are having this issue, you could temporarily use this fork:
```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/ricardo-lobo/laravel-websockets"
    }
  ],
```

**Comment by ricardo-lobo** [comment]
> For anyone who are having this issue, you could temporarily use this fork:
> 
> ```
> "repositories": [
>     {
>       "type": "git",
>       "url": "https://github.com/ricardo-lobo/laravel-websockets"
>     }
>   ],
> ```

Thats how I solved! Until this is merged or the issue is fixed.

**Comment by shahriar-b** [comment]
24 days already! what are you waiting for?

**Pull request merged**
