### PR TITLE
Fix for dependency upgrade

### PR DESCRIPTION
**Pull request by gabrieliuga**
fixing issue #222
+ DnsResolver no longer extends React/Dns/Resolver as it's now a final class
+ StartWebSocketServer:getDnsResolver returns ResolverInterface to comply with new react/dns policy

### CODE REVIEW

**Comment by deviouspk** [comment]
Add this to the composer file please:
react/dns:^1.1

The resolverinterface is newly introduced in 1.1. This to avoid that people who are on react/dns 1.0 get issues.

**Comment by TheBigK** [comment]
Will this be merged in the main branch?

**Comment by gabrieliuga** [comment]
Waiting for @mpociot to accept/deny the request.

**Comment by mpociot** [comment]
Thank you!

**Comment by TheBigK** [comment]
We'll still have to wait till a new version of laravel-websockets is released, right? I tried updating but it still throws the same issue.

**Comment by deviouspk** [comment]
@mpociot please publish a new release the package is broken at the moment

**Comment by ereztdev** [comment]
Can anyone please paste the build I should require to fix `beyondcode/laravel-websockets` package issue? I am currently on version `^1.1` and it has breaking changes.

**Comment by deviouspk** [comment]
Dev-master :p

**Comment by judahnator** [comment]
Any movement on this? Been broken for quite some time...

**Comment by gabrieliuga** [comment]
use dev-master in composer.json to grab the fix as there is no release yet with the fix
`
composer require beyondcode/laravel-websockets:dev-master
`

**Pull request merged**
