### PR TITLE
update dependency for Laravel 10

### PR DESCRIPTION
**Pull request by RF1705**

### CODE REVIEW

**Comment by geeksesi** [comment]
merge please

**Comment by goper-leo** [comment]
What's the hold up?

**Comment by parallels999** [comment]
> What's the hold up?

Abandoned

**Review by nextgen-jp — APPROVED** [review]

**Comment by HilalLko** [comment]
@rennokki 
Possible to review this PR?

**Comment by beingssudeep** [comment]
@rennokki

**Pull request closed without merging**
