### PR TITLE
[2.x] Add Custom API Route Handlers

### PR DESCRIPTION
**Pull request by simonbuehler**
hi, 

this should fix https://github.com/beyondcode/laravel-websockets/issues/660

### CODE REVIEW

**Comment by simonbuehler** [comment]
@rennokki any plans to merge ?

**Comment by rennokki** [comment]
It's a bit tricky because you can already call the `\BeyondCode\LaravelWebSockets\Facades\WebSocketRouter::get` in your `AppServiceProvider`'s `boot` method.

**Comment by simonbuehler** [comment]
i see - currently #661 is in the way for the  `WebSocketRouter::get` approach therefore i made it work this way - in the end its a matter of taste if doing this via explicit code or config is preferred

**Comment by simonbuehler** [comment]
Actually it throws even anothe error when trying to bind to Class which extends `BeyondCode\LaravelWebSockets\API\Controller` 

``` php
   Illuminate\Contracts\Container\BindingResolutionException

  Target [BeyondCode\LaravelWebSockets\Contracts\ChannelManager] is not instantiable while building [App\API\SelectRandomUserFromChannel].

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1038
    1034▕         } else {
    1035▕             $message = "Target [$concrete] is not instantiable.";
    1036▕         }
    1037▕
  ➜ 1038▕         throw new BindingResolutionException($message);
    1039▕     }
    1040▕
    1041▕     /**
    1042▕      * Throw an exception for an unresolvable primitive.

      +17 vendor frames
  18  app/Providers/AppServiceProvider.php:31
      Illuminate\Support\Facades\Facade::__callStatic("get")

      +7 vendor frames
  26  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider))
```

**Comment by rennokki** [comment]
It's weird because the issue https://github.com/beyondcode/laravel-websockets/issues/661 that you sent to me has a different error message than the one you specified now.

The error message that you specified now it's because the ChannelManager class is not instantiable. The sockets cannot be accessed outside the server, only within the files that are strictly used [by the start command](https://github.com/beyondcode/laravel-websockets/blob/2.x/src/Console/Commands/StartServer.php#L107-L116)

Show me a sample of your code using `WebSocketRouter::get` and the controller you're trying to implement. Having a config file that does that is just duplicating the functionality.

**Comment by simonbuehler** [comment]
Therefor i think my pull request is the only way to hook into the correct server context - for example this class

``` php
<?php

namespace App\API;

use BeyondCode\LaravelWebSockets\API\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use React\Promise\PromiseInterface;
use function React\Promise\all;


class GetFullUsersInfoFromChannel extends Controller
{
    /**
     * @param Request $request
     * @return \React\Promise\Promise|PromiseInterface|void
     */
    public function __invoke(Request $request)
    {
        return all($this->channelManager
            ->getChannelMembers($request->appId, $request->channelName)
            ->then(function ($members) use ($request) {
                return all([
                    'users' => all(collect($members)->map(function ($user) use ($request) {
                        $this->channelManager->getMemberSockets($user->user_id, $request->appId, $request->channelName)
                            ->then(function ($sockets) use ($user) {
                                $user->sockets = $sockets; //resolved
                                return $user;
                            });
                        return $user; //resolved
                    })->values()->toArray())]);
            }));
    }
}
```

and 

``` 
'custom_handlers' => [

         '/apps/{appId}/userinfo/{channelName}' => ['get' , \App\API\GetFullUsersInfoFromChannel::class],

    ],
```

can't be done in the `AppServiceProvider` context

**Comment by simonbuehler** [comment]
hi,

was this rejected or closed by mistake?

**Comment by rennokki** [comment]
2.x got closed

**Comment by rennokki** [comment]
As far as I checked out, there is a counter-pattern on your implementation, since you're trying to resolve the sync module in async by resolving all the promises.

**Comment by simonbuehler** [comment]
i first tried to make the FullfilledPromise JsonSeralizable but the reactphp guys [in my PR](https://github.com/reactphp/promise/pull/182#issuecomment-76382870) lead me to this solution which works fine here.

What would you suggest?

**Comment by simonbuehler** [comment]
this would basically re-enable the lost functionality of #150

**Comment by rennokki** [comment]
Please see https://github.com/beyondcode/laravel-websockets/pull/735, it was a bit off to find out that custom routes accidentally got registered at runtime anytime the kernel ran, not just when the websocket command ran.

**Comment by rennokki** [comment]
@simonbuehler The only difference is that another function may be used to differ from the registration ones:

```php
WebSocketsRouter::addCustomRoute('GET', '/my-websocket', \App\MyCustomWebSocketHandler::class);
```

**Pull request closed without merging**
