### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/beyondcode/laravel-websockets/pull/930/commits/22d32dde1cd1ad6edf6520c7c03a244a7dac59ef?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-websockets.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "beyondcode/laravel-websockets": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by joecampo** [comment]
I tested this PR, but had issues. Found that `symfony/http-kernel` has to also be bumped to `^6.0`

**Comment by jasonmccreary** [comment]
@joecampo, yeah, that was our bad. Shift didn't account for Symfony dependencies. It will in the future.

**Comment by joecampo** [comment]
@jasonmccreary That's awesome, thanks for all you do! Shift is such an awesome product :)

**Pull request closed without merging**
