### PR TITLE
[WIP] Removed facades

### PR DESCRIPTION
**Pull request by 4levels**
Facades are optional in Laravel and any library should be able to work without them.
This PR tries to remove all use of Facades

### CODE REVIEW

**Comment by 4levels** [comment]
Hi core-devs,

I could use some help in fixing the unit test, I don't get what's causing this.. (hence the WIP in the title) ;-)

**Comment by 4levels** [comment]
Hi @mpociot,

I'm not sure how I can make the tests succeed.  This repository has no artisan, no database config etc etc so it seems the test itself is not going to work at all, no matter what I change in the code.  Is this normal?

**Comment by freekmurze** [comment]
Thank you for this, but I'm thinking the use of facades is fine. Nobody reported any trouble caused by facades and they make to code more clear.

**Comment by 4levels** [comment]
Hi @freekmurze,

Please don't just close pull requests because you think something, and frankly, you're thinking wrong - see eg. https://github.com/laravel/passport/issues/260  Do your homework about Facades, they should remain optional no matter what library one chooses to add.
This package doesn't work in any of my projects since I never enable facades.  Imho facades obfuscate code and allow for unpredictable results if used without caution. 

Regarding the failing unit test: there's no way I can make the WebSocketsStatisticsControllerTest pass in any of the branches of this repo.  This test seems flawed: it assumes way too many things (hostname, running websocket server, ..) for it to succeed in a test environment.

cc: @mpociot

**Comment by mpociot** [comment]
I agree with Freek on this one and I do not see an issue in using facades - especially since most of them are our own classes.

**Comment by 4levels** [comment]
Guys, 

Have you even tried adding this project in a Laravel project without facades enabled?

This is so sad, it seems like most Laravel library owners have the same pedantic attitude as Taylor himself!

I guess I'll be using my form forever then, lame..

**Pull request closed without merging**
