### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by diegotibi**
I know it's a duplicate but this includes also Symfony 6

### CODE REVIEW

**Comment by fredsal** [comment]
Closes #943 
Closes #945

**Comment by mpociot** [comment]
Thank you very much. Could you send this PR to the 1.x branch as well?

**Comment by diegotibi** [comment]
@mpociot sure, done! #948

**Comment by tntsoft** [comment]
When can we expect a minor release that will include this commit?

**Comment by bmbBAMBUS** [comment]
I still get #945 issue on clear Laravel 9 project.

**Comment by diegotibi** [comment]
> I still get #945 issue on clear Laravel 9 project.

That's because a new realease hasn't been tagget yed.

Temporary solution: set  your composer dependancy to dev-master

**Comment by tntsoft** [comment]
@bmbBAMBUS Fork the repository and set a vcs at the top of composer.json:
`  "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/[PATH TO FORKER REPO]"
        }
    ],`

**Comment by bmbBAMBUS** [comment]
Oh sorry, didn't notice that release hasn't been tagged.

@diegotibi , @tntsoft  Thank you for advices!

**Comment by lucasantonioedmond** [comment]
Do you have any plans to update the package to Laravel 9?

I tested it now and I still have the same problem.

**Comment by tntsoft** [comment]
> Do you have any plans to update the package to Laravel 9?
> 
> I tested it now and I still have the same problem.

This is definitely working. Make sure your composer file import looks like this:

>  "beyondcode/laravel-websockets": "^1.13",

**Comment by lucasantonioedmond** [comment]
> > Você tem planos de atualizar o pacote para o Laravel 9?
> > Testei agora e continuo com o mesmo problema.
> 
> Isso definitivamente está funcionando. Certifique-se de que a importação do arquivo do compositor tenha esta aparência:
> 
> > "beyondcode/laravel-websockets": "^1.13",

this is the error

Problem 1
    - Root composer.json requires beyondcode/laravel-websockets 1.13 -> satisfiable by beyondcode/laravel-websockets[1.13.0].
    - beyondcode/laravel-websockets 1.13.0 requires guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by fredsal** [comment]
[Laravel 9.x Demo](https://github.com/beyondcode/laravel-websockets-demo/pull/22)

**Comment by diegotibi** [comment]
Probably my fault, I've forgot to bump guzzlehttp on 1.x branch...

**Comment by lucasantonioedmond** [comment]
> 

going to upgrade a 1.14 to fix this??

**Comment by banyu-wigara** [comment]
> > 
> 
> going to upgrade a 1.14 to fix this??

Probably ...

**Comment by fredsal** [comment]
`composer require "beyondcode/laravel-websockets:dev-master"`

**Comment by alecpl** [comment]
Could someone push this to 2.x branch?

**Comment by MrReeds** [comment]
> Could someone push this to 2.x branch?

Since 2.x is not released, why not use the 2.0.0-beta? I tried it and it seems to work

**Pull request merged**
