### PR TITLE
Adds opt-in support for Pusher 6.x

### PR DESCRIPTION
**Pull request by DarkGhostHunter**

### CODE REVIEW

**Comment by matystu** [comment]
Any estimated time of merging this? I really want to use pusher 6 on my new project. Thanks for all of your work on this package

**Comment by DarkGhostHunter** [comment]
> Any estimated time of merging this? I really want to use pusher 6 on my new project. Thanks for all of your work on this package

Until Laravel 8.x supports Pusher 6.x. In theory, it shouldn't have a problem. You can test by using Laravel and trying to `composer require pusher/pusher-http-php: 6.1`.

**Comment by DarkGhostHunter** [comment]
It has been approved on Laravel side.

**Comment by mpociot** [comment]
Thank you. I'll take care of this in the next couple of days as I'm trying to finish up the last missing pieces for a 2.0 stable release

**Comment by shehi** [comment]
Can we have an update on this one please?

**Comment by Rhydium** [comment]
Any update on this? It's been another 26 days 😛

**Comment by DarkGhostHunter** [comment]
I’ll personally wait until the first 6.x patch, if there is none. 

Italo Baeza C.

**Comment by DarkGhostHunter** [comment]
I think it's safe now to support Pusher 7.0.

**Pull request closed without merging**
