### PR TITLE
[1.x] Update pusher/pusher-php-server versions

### LINKED ISSUE #943: Laravel 9 Support
Please, add support for Laravel 9

### LINKED ISSUE #945: Support for laravel 9
the package keeps throwing the following error for laravel 9
 - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version)
 by a partial update and that version does not match. Make sure you list it as an argument for the update command.

- Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require illuminate/console ^6.0|^7.0|^8.0 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8
.x-dev] but these were not loaded, likely because it conflicts with another require.

### LINKED ISSUE #951: Miss versions pusher/pusher-php-server in required composer.json
The new version: 1.13 the composer json not include  "pusher/pusher-php-server": "^3.0|^4.0|^5.0|**^6.0|^7.0**", in required composer.json

``` Problem 1
    - beyondcode/laravel-websockets[1.13.0, ..., 1.x-dev] require pusher/pusher-php-server ^3.0|^4.0|^5.0 -> found pusher/pusher-php-server[dev-master, 3.0.0, ..., v3.4.1, v4.0.0, ..., v4.1.5, v5.0.0, ...
, 5.0.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires beyondcode/laravel-websockets ^1.13 -> satisfiable by beyondcode/laravel-websockets[1.13.0, 1.x-dev].
```

in branch master with then.

- master
https://github.com/beyondcode/laravel-websockets/blob/master/composer.json

- v.1.13.0
https://github.com/beyondcode/laravel-websockets/blob/1.13.0/composer.json

### LINKED ISSUE #956: Still not compatible with laravel 9
Hi whenever I'm trying to install the package it is throwing error in laravel 9

```
Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/laravel-websockets ^1.13 -> satisfiable by beyondcode/laravel-websockets[1.13.0, 1.x-dev].
    - beyondcode/laravel-websockets[1.13.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### PR DESCRIPTION
**Pull request by joecampo**
Hi there,

This PR updates the versions for pusher-php-server to match the master branch. In Laravel 9 I believe you need to use version ^7.0.

- This will make the 1.x version useable in Laravel 9.
- All of these changes are already reflected in the master branch

Fixes #951 
Fixes #956
Fixes #945 
Fixes #943

### CODE REVIEW

**Comment by PaolaRuby** [comment]
Needs others changes
#895 
#830
#908

**Comment by erikn69** [comment]
for laravel 9.x maybe try `composer require "beyondcode/laravel-websockets:dev-master"`

**Comment by joecampo** [comment]
@PaolaRuby Thanks! I've implemented those fixes for tests as applicable to the 1.x branch & added support for `GuzzleHttp/Psr7` ^2.0 – Composer no longer downgrades that dependency and everything seems to be in working order.

**Comment by erikn69** [comment]
`GuzzleHttp/Psr7` must be `1.7|2.0`, `1.5,1.6` are incompatible witn `2.0`

**Comment by joecampo** [comment]
@erikn69 fixed!

**Comment by mpociot** [comment]
Thank you!

**Pull request merged**
