### PR TITLE
[fix] Check for key app on authorization

### LINKED ISSUE #622: PHP pusher library can connect without valid appkey
Hi,

I've tested this in the latest version, and an older one and it appears that the application is allowed API requests from the PHP pusher library (and probably others) without a valid appkey. Only the app secret is checked.

### PR DESCRIPTION
**Pull request by rennokki**
It does better by searching for a key instead of a secret.

Closes #622

### CODE REVIEW

**Comment by lovetoast** [comment]
Unless I'm mistaken, this only checks in the statistics modules?

**Comment by rennokki** [comment]
@lovetoast It's a middleware that's used in sending events.

**Comment by lovetoast** [comment]
@rennokki I thought so, but I tested it and it still allowed the request through, so I also just put a die() in this function and it still allowed it through, there must be somewhere else?

**Comment by lovetoast** [comment]
> events

Merry Christmas! I tried this again, but pretty sure it is not the write place, and I was not able to find the correct place for the APP KEY code.

**Pull request merged**
